blog/blog/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('news/', include('news.urls')),
    path('accounts/', include('users.urls')),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/main/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='home'),
    path('home', views.index, name='home'),
    path('about', views.about, name='about'),
]

blog/users/models.py
from django.db import models
from django.contrib.auth.models import BaseUserManager, AbstractBaseUser

ACCOUNT_TYPE = [
    ('1', 'Base'),
    ('2', 'Expert'),
    ('3', 'Pro'),
]


class MyUserManager(BaseUserManager):

    def create_user(self, email, fio, telegram, money, companys, password=None, account_type=ACCOUNT_TYPE[0]):
        if not email:
            raise ValueError('Users must have an email address')

        user = self.model(
            email=self.normalize_email(email),
            fio=fio,
            telegram=telegram,
            money=money,
            companys=companys,
            accout_type=account_type
        )

        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self, email, password=None, account_type=ACCOUNT_TYPE[2]):
        user = self.create_user(
            email,
            password=password,
            fio='admin',
            telegram='admin',
            companys=0,
            money=0,
            account_type=account_type
        )
        user.is_admin = True
        user.save(using=self._db)
        return user


class MyUser(AbstractBaseUser):
    email = models.EmailField('Email', max_length=255, unique=True)
    fio = models.CharField('ФИО', max_length=100, default='', blank=False)
    telegram = models.CharField('Telegram', max_length=100, default='', blank=False)
    money = models.IntegerField('Баланс', default=0, blank=False)
    companys = models.IntegerField('Кампаний', default=0, blank=False)
    is_active = models.BooleanField(default=True, blank=False)
    is_admin = models.BooleanField(default=False, blank=False)
    account_type = models.CharField(choices=ACCOUNT_TYPE, max_length=10, default='1', verbose_name='Тип аккаунта')
    avatar = models.ImageField('Аватар', upload_to='images/', default='static/main/img/stock_avatar.png', null=True)

    objects = MyUserManager()

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['fio', 'telegram']

    class Meta:
        verbose_name = 'Пользователь'
        verbose_name_plural = 'Пользователи'

    def __str__(self):
        return self.email

    def has_perm(self, perm, obj=None):
        return True

    def has_module_perms(self, app_label):
        return True

    @property
    def is_staff(self):
        return self.is_admin


class Message(models.Model):
    text_message = models.CharField('Текст', max_length=500, default='', blank=False)
    from_message = models.ForeignKey('MyUser', blank=True, null=True, default=None, on_delete=models.CASCADE, related_name='from_message')
    to_message = models.ForeignKey('MyUser', blank=True, null=True, default=None, on_delete=models.CASCADE, related_name='to_message')
    time = models.DateTimeField('Время отправки')

    def __str__(self):
        return self.text_message

    class Meta:
        verbose_name = 'Сообщение'
        verbose_name_plural = 'Сообщения'


class Offer(models.Model):
    title = models.CharField('Название', max_length=200, default='', blank=False)
    description = models.CharField('Описание', max_length=1000, default='', blank=False)
    dropship_price = models.IntegerField('Цена для дропа', default=0, blank=False)
    price = models.IntegerField('Цена', default=0, blank=False)
    profit = models.IntegerField('Профит', default=0, blank=False)
    image = models.ImageField('Изображение', upload_to='images/', default='static/main/img/offer_default.png', null=True)

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'Оффер'
        verbose_name_plural = 'Офферы'


class UserOffers(models.Model):
    offer_owner = models.ForeignKey(MyUser, on_delete=models.CASCADE, related_name="email_user", verbose_name='Пользователь')
    offer_title = models.ForeignKey(Offer, on_delete=models.CASCADE, related_name="title_offer", verbose_name='Название оффера')
    offer_views = models.IntegerField('Просмоторы', default=0, blank=False)
    offer_sells = models.IntegerField('Продажи', default=0, blank=False)
    offer_profit = models.IntegerField('Профит', default=0, blank=False)
    time = models.DateTimeField('Время добавления', default=0, blank=False)

    def __str__(self):
        return str(self.offer_title)

    class Meta:
        verbose_name = 'Пользовательский оффер'
        verbose_name_plural = 'Пользовательские офферы'

blog/main/views.py
from django.shortcuts import render


def index(request):
    data = {
        'title': 'Main page',
    }
    return render(request, 'main/index.html', data)


def about(request):
    data = {
        'title': 'About page',
    }
    return render(request, 'main/about.html', data)

blog/main/templates/main/about.html
{% extends 'main/layout.html' %}

{% block title %}{{ title }}{% endblock %}

{% block content %}
    <div class="features">
        <h1>{{ title }}</h1>
        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Amet consequatur corporis deserunt dolore dolorem error modi possimus quasi rerum. Accusantium consequatur dicta doloribus perferendis qui tempore ullam? Cum, enim, neque.</p>
        <a href="{% url 'home' %}" class="btn btn-success">Go to Main page</a>
        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Amet consequatur corporis deserunt dolore dolorem error modi possimus quasi rerum. Accusantium consequatur dicta doloribus perferendis qui tempore ullam? Cum, enim, neque.</p>
        <a href="{% url 'home' %}" class="btn btn-danger">Go to Main page</a>
    </div>
{% endblock %}

blog/main/templates/main/header.html
{% load static %}
<div class="header">
    {% if user.is_authenticated %}
        <span> Hi {{ user.email }}!</span>
        <a href="{% url 'profile' %}"><img class="avatar" src="../{{ user.avatar }}" alt=""></a>
        <a class="btn btn-warning login-form" href="{% url 'logout' %}">Press to LogOut</a>
    {% else %}
        <span>You are not logged in</span>
        {% if 'login' in request.get_full_path %}
            <a class="btn btn-success login-form" href="{% url 'register' %}">Press to Register</a>
        {% endif %}
        {% if 'register' in request.get_full_path %}
            <a class="btn btn-outline-primary login-form" href="{% url 'login' %}">Press to LogIn</a>
        {% endif %}
        {% if not 'register' in request.get_full_path and not 'login' in request.get_full_path %}
            <a class="btn btn-success login-form" href="{% url 'register' %}">Press to Register</a>
            <a class="btn btn-outline-primary login-form" href="{% url 'login' %}">Press to LogIn</a>
        {% endif %}
    {% endif %}
</div>

blog/main/templates/main/index.html
{% extends 'main/layout.html' %}

{% block title %}{{ title|upper }}{% endblock %}

{% block content %}
    <div class="features">
        <h1>{{ title }}</h1>
        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Amet consequatur corporis deserunt dolore dolorem error modi possimus quasi rerum. Accusantium consequatur dicta doloribus perferendis qui tempore ullam? Cum, enim, neque.</p>
        <a href="{% url 'about' %}" class="btn btn-warning">Go to About page</a>
    </div>
{% endblock %}

blog/main/templates/main/layout.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.2/css/all.css">
    <link rel="stylesheet" href="{% static 'main/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'main/css/main.css' %}">
    <link rel="shortcut icon" href="{% static 'main/img/icon.png' %}" type="image/x-icon">
</head>
<body>
    {% include 'main/nav.html' %}
    {% include 'main/header.html' %}
    <main>
        {% block content %}
        {% endblock %}
    </main>

    {% block script %}
    {% endblock %}

    <script src="{% static 'main/js/nav.js' %}"></script>

</body>
</html>

blog/main/templates/main/my_offers.html
{% extends 'main/layout.html' %}

{% block title %}{{ title }}{% endblock %}

{% load static %}
{% load crispy_forms_tags %}
{% block content %}
    <div class="features">
        <table>
            <thead>
                <tr>
                    <th>№</th>
                    <th>Название</th>
                    <th>Изображение</th>
                    <th>Просмотры</th>
                    <th>Продажи</th>
                    <th>Профит</th>
                    <th>Дата добавления</th>
                    <th>Действие</th>
                </tr>
            </thead>
            <tbody>
                {% for offer in confirmed_offers %}
                    <tr class="offer my_offers">
                        <td>{{ offer.id }}</td>
                        <td class="title_offer">{{ offer.inst.offer_title }}</td>
                        <td class="image"><img src="{{ offer.img.image }}" alt=""></td>
                        <td>{{ offer.inst.offer_views }}</td>
                        <td>{{ offer.inst.offer_sells }}</td>
                        <td>{{ offer.inst.offer_profit }}</td>
                        <td>{{ offer.inst.time }}</td>
                        <td class="action">
                            <form class="buy_form" method="post">
                                {% csrf_token %}
                                <input type="hidden" name="offer_id" value="{{ offer.inst.pk }}">
                                <button class="btn btn-danger" type="submit">Удалить</i></button>
                            </form>
                        </td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
{% endblock %}

blog/main/templates/main/nav.html
{% load static %}
<aside>
    <img src="{% static 'main/img/logo.png' %}" alt="logo">
    <h3>Navigation</h3>
    <ul>
        <a href="{% url 'home' %}"><li><i class="fas fa-home"></i> Main page</li></a>
        <a href="{% url 'about' %}"><li><i class="fas fa-question-circle"></i> About</li></a>
        <a href="{% url 'news_home' %}"><li><i class="fas fa-rss-square"></i> News</li></a>
        <a href="{% url 'profile' %}"><li><i class="fa fa-user" aria-hidden="true"></i> My Profile</li></a>
        <a href="{% url 'chat' %}"><li><i class="fa fa-comment" aria-hidden="true"></i> Chat</li></a>
        <a href="{% url 'all_offers' %}"><li><i class="fas fa-luggage-cart"></i> Offers</li></a>
        <a href="{% url 'my_offers' %}"><li><i class="far fa-clipboard"></i> My Offers</li></a>
        {% if user.is_authenticated %}
            <a href="{% url 'create' %}"><li><button class="btn btn-info"><i class="fa fa-plus-circle"></i> Add news</button></li></a>
        {% endif %}
    </ul>
</aside>

blog/main/templates/main/offers.html
{% extends 'main/layout.html' %}

{% block title %}{{ title }}{% endblock %}

{% load static %}
{% load crispy_forms_tags %}
{% block content %}
    <div class="features">
        <table>
            <thead>
                <tr>
                    <th>№</th>
                    <th class="title_offer">Название</th>
                    <th>Описание</th>
                    <th>Цена</th>
                    <th>Профит</th>
                    <th>Изображение</th>
                    <th>Действие</th>
                </tr>
            </thead>
            <tbody>
                {% for offer in all_offers %}
                    <tr class="offer">
                        <td class="id">{{ offer.id }}</td>
                        <td class="title_offer">{{ offer.inst.title }}</td>
                        <td class="description">{{ offer.inst.description }}</td>
                        <td class="prices">{{ offer.inst.price }}</td>
                        <td class="prices">{{ offer.inst.profit }}</td>
                        <td class="image"><img src="../{{ offer.inst.image }}" alt=""></td>
                        <td class="action">
                            <form class="buy_form" method="post">
                                {% csrf_token %}
                                <input type="hidden" name="offer_id" value="{{ offer.inst.pk }}">
                                {% if offer.conf %}
                                    <button disabled class="btn btn-secondary" type="submit">Добавлен</i></button>
                                {% else %}
                                    <button class="btn btn-success" type="submit">Добавить</i></button>
                                {% endif %}
                            </form>
                        </td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
{% endblock %}

blog/main/templates/main/profile.html
{% extends 'main/layout.html' %}

{% block title %}{{ title }}{% endblock %}

{% block content %}
    <div class="features">
            <h1>{{ title }}</h1>
        <div class="flex">
            <div class="block">
                <p>Почта</p>
                <p>{{ user.email }}</p>
            </div>
            <div class="block">
                <p>ФИО </p>
                <p>{{ user.fio }}</p>
            </div>
            <div class="block">
                <p>Telegram</p>
                <p>{{ user.telegram }}</p>
            </div>
            <div class="block">
                <p>Кампании</p>
                <p>{{ user.companys }}</p>
            </div>
            <div class="block">
                <p>Баланс</p>
                <p>{{ user.money }}</p>
            </div>
            <div class="block">
                <p>Тип аккаунта</p>
                <p>{{ user.get_account_type_display }}</p>
            </div>
            {% if user.is_admin %}
                <div class="block is_admin">Роль: Admin</div>
            {% else %}
                <div class="block">Роль: User</div>
            {% endif %}
        </div>
    </div>
{% endblock %}